# Spring properties
spring:
  application:
     name: socialreview-microservice


# Server configuration
server:
  context-path: /micro
  port: 8080


# Cloudant Configuration
cloudant:
    db: socialreviewdb
    username: xxxx
    password: zzzzz
    url: https://xxxx-yyyy-bluemix.cloudant.com
